env = "development"

[server]
port = 3001

    [server.cors]
    allow_credentials = true
    allowed_headers = ["*"]
    allowed_methods = ["OPTIONS", "GET", "POST"]
    allowed_origins = ["http://localhost:3000"]
    max_age = "5m"

    [server.jwt]
        [server.jwt.access_token]
        audience = ["*"]
        expires_at = "10s"
        issuer = "localhost"
        not_before = "0s"
        secret = "this_should_really_be_something_else"

        [server.jwt.refresh_token]
        audience = ["*"]
        expires_at = "168h"
        issuer = "localhost"
        not_before = "0s"
        secret = "this_should_definitely_be_something_else"

        [server.jwt.refresh_cookie]
        domain = "localhost"
        http_only = true
        path = "/"
        same_site = "strict"
        secure = false

    [server.log]
    level = "debug"

    [server.graphql]
    schema = "./schema.graphql"

[database]
    [database.main]
    dbname = "dev"
    driver = "postgres"
    host = "localhost"
    password = "dev"
    port = 5432
    schema = "public"
    sslmode = "disable"
    user = "dev"

    [database.test]
    dbname = "test"
    driver = "postgres"
    host = "localhost"
    password = "test"
    port = 5432
    schema = "public"
    sslmode = "disable"
    user = "test"

    [database.migrations]
    location = "file://./database/migrations"
    run_on_start = true

    [database.models]
    blacklist = ["schema_migrations"]
    no-tests = true
    output = "./src/models"
    struct-tag-casing = "camel"
    wipe = true
