env = "development"

[server]
port = 3001

    [server.cors]
    max_age = "5m"
    allow_credentials = true
    allowed_origins = ["http://localhost:3000"]
    allowed_methods = ["OPTIONS", "GET", "POST"]
    allowed_headers = ["*"]

    [server.jwt]
        [server.jwt.access_token]
        audience = ["*"]
        issuer = "localhost"
        expires_at = "10s"
        not_before = "0s"
        secret = "this_should_really_be_something_else"

        [server.jwt.refresh_token]
        audience = ["*"]
        issuer = "localhost"
        expires_at = "168h"
        not_before = "0s"
        secret = "this_should_definitely_be_something_else"

    [server.log]
    level = "debug"

    [server.graphql]
    schema = "./schema.graphql"

[database]
    [database.main]
    driver = "postgres"
    dbname = "dev"
    user = "dev"
    password = "dev"
    host = "localhost"
    port = 5432
    schema = "public"
    sslmode = "disable"

    [database.test]
    driver = "postgres"
    dbname = "test"
    user = "test"
    password = "test"
    host = "localhost"
    port = 5432
    schema = "public"
    sslmode = "disable"

    [database.migrations]
    location = "file://./database/migrations"
    run_on_start = true

    [database.models]
    wipe = true
    output = "./src/models"
    struct-tag-casing = "camel"
