name: Template

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: test
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.14
      - name: Run Tests
        run: |
          cd template
          ./core.sh migrate --only-test up
          cd src
          go test ./test/...

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        name: Publish docker image to GitHub
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: scott-rc/core/core
          tag_with_ref: true
          tag_with_sha: true
          path: ./template
      - uses: docker/build-push-action@v1
        name: Publish docker image to Heroku
        with:
          username: _
          password: ${{ secrets.HEROKU_AUTH_TOKEN }}
          registry: registry.heroku.com
          repository: core-go/web
          tag_with_ref: true
          tag_with_sha: true
          path: ./template

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: publish
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_AUTH_TOKEN }}
        run: |
          heroku container:login
          heroku container:release web --app=core-go